### ISSUE TITLE
error: terminated by signal SIGSEGV

### ISSUE THREAD

**Issue by Brixy** [ventojs/tree-sitter-vento#2]
Hi guys,

The helix editor [supports vento](https://github.com/helix-editor/helix/blob/master/languages.toml#L3997-L4006).

I just noticed the following problem, which is caused by `tree-sitter-vento` as far as I can tell:

```
echo {{ site.url }} > test.vto
hx test.vto
```

Error message:

> Job 1, 'hx test.vto' terminated by signal SIGSEGV (Address boundary error)

Yet, everything works correctly without a dot within in braces:

```
echo {{ siteurl }} > test.vto
hx test.vto
```

Thank you!

**Comment by wrapperup** [comment]
I can't replicate the issue in Helix 24.07 in either Windows 10 (19045.5131) nor Ubuntu 22.04.2. What OS are you using?

**Comment by Brixy** [comment]
Sorry, I didn't mention that I compiled helix from source.

The vento language was apparently just recently added to helix.

But if you add [these lines](https://github.com/helix-editor/helix/blob/master/languages.toml#L3997-L4006) to `$XDG_CONFIG_HOME/helix/languages.toml`, it should be possible to reproduce this issue with helix's stable version.

**Comment by oscarotero** [comment]
I'm not familiarized with helix.
Maybe @wrapperup can help with this.

**Comment by wrapperup** [comment]
Sorry for the wait, got busy over the holidays! This one was pretty nightmarish to track down, but it will be fixed in the next version. Thank you for your patience! Looks like the tests are broken too...

**Comment by wrapperup** [comment]
Changes are available, though the language file for Helix is still locked to the broken version. You may need to manually update the `languages.toml` file to the latest revision until then.

I've gone ahead and opened a PR to bump the version https://github.com/helix-editor/helix/pull/12368, and for any Neovim users the `nvim-treesitter` lockfile is automatically bumped by a bot, I will close the issue once those two are resolved.

**Comment by Brixy** [comment]
Thank you very much for your work on this issue. I really appreciate it.

Everything works perfectly now. And I'm glad to see that your PR has been merged.

Thanks again!
